### ISSUE TITLE
Error: Invalid or corrupt jarfile /usr/local/bin/apgdiff.jarc when running migrations init

### ISSUE THREAD

**Issue by slagfart** [subzerocloud/subzero-starter-kit#11]
Hi folks, 

I'm following the tutorial page here: https://docs.subzero.cloud/managing-migrations/ and I get the error `Error: Invalid or corrupt jarfile /usr/local/bin/apgdiff.jar` when trying to run the managing migrations section. 

```
$ subzero migrations init
Writing database dump to /Users/jambo/PycharmProjects/udemy_pc/tmp/dev-initial.sql
Created sqitch.conf
Created sqitch.plan
Created deploy/
Created revert/
Created verify/
Created deploy/0000000001-initial.sql
Created revert/0000000001-initial.sql
Created verify/0000000001-initial.sql
Added "0000000001-initial" to sqitch.plan
Diffing /Users/jambo/PycharmProjects/udemy_pc/tmp/dev-initial.sql and /Users/jambo/PycharmProjects/udemy_pc/tmp/prod-initial.sql
Writing the result to /Users/jambo/PycharmProjects/udemy_pc/db/migrations/revert/0000000001-initial.sql
Error: Invalid or corrupt jarfile /usr/local/bin/apgdiff.jar

Copying /Users/jambo/PycharmProjects/udemy_pc/tmp/dev-initial.sql to /Users/jambo/PycharmProjects/udemy_pc/db/migrations/deploy/0000000001-initial.sql
```
I know you use apgdiff to generate your migration file - I could [download it to](https://github.com/fordfrog/apgdiff/tree/develop/releases) /usr/local/bin? But also there must be a more elegant way that keeps apgdiff up to date. 
Thanks!

**Comment by ruslantalpa** [comment]
there was a corrupted build which is fixed now, please run `docker pull subzerocloud/subzero-cli-tools` then it should work
