### ISSUE TITLE
Question - plan to add JS support for request hook?

### ISSUE THREAD

**Issue by cjnqt** [subzerocloud/subzero-starter-kit#21]
Do you plan to support hooking into the request lifecycle using JS scripts?

**Comment by ruslantalpa** [comment]
yes i am, note however that this "js code" is going to be running in withing nginx using [njs](https://nginx.org/en/docs/njs/) so it will not be like using node, your functions will mostly need to be "pure" (no external network calls) and if you'll need to use node modules, the code will need to be "packed" with something like webpack ... i am researching this right now, how to make it easier to run idiomatic node code withing njs.

theoretically nothing is stopping you from taking the openresty image and "bundling" your own js hooks ... but it's a chore .... lots of things need to be set just right for this to work similar to the lua hooks
