### ISSUE TITLE
Consider pg_amqp instead of subzerocloud/pg-amqp-bridge

### ISSUE THREAD

**Issue by BjornMelgaard** [subzerocloud/subzero-starter-kit#5]
https://github.com/omniti-labs/pg_amqp

As I understand it will allow to bypass postgres notify/listen

**Comment by ruslantalpa** [comment]
This is not a separate executable as pg-amqp-bridge, it’s a pg module, you have to compile it and load it into pg and you can’t do that with things like RDS. Your suggestion works only if you manage your own pg instance. If that is the case then sure, it’s a good solution, accomolishes the same thing (as long as it reliable and does things like reconnect on disconnect like the bridge does). One advantage of your suggestion that i see is that you can roll back a transaction when you fail to deliver a message to rabbit, while with the bridge, that is not possible
