### ISSUE TITLE
trying example -> all todo.id are not integers and all are the same

### ISSUE THREAD

**Issue by ghost** [subzerocloud/subzero-starter-kit#6]
Following this with fresh installation:

https://docs.subzero.cloud/tutorial/

![image](https://user-images.githubusercontent.com/37046197/45036390-61291f00-b02a-11e8-91ce-461f78a9bb98.png)

My curl results reply with some random varchar:

<img width="572" alt="wqetqwe" src="https://user-images.githubusercontent.com/37046197/45036692-28d61080-b02b-11e8-9ab6-62cdebd15fcb.png">

![image](https://user-images.githubusercontent.com/37046197/45036721-3e4b3a80-b02b-11e8-9af2-e3b712ae3966.png)

**Comment by TameBadger** [comment]
This is how that view is defined

```
create or replace view todos as
select data.relay_id(t.*) as id, id as row_id, todo, private, (owner_id = request.user_id()) as mine from data.todo t;
alter view todos owner to api;
```

You'll see the function `relay_id` defined in `src/api/data` as

```
create or replace function relay_id(todo) returns text as $$
select encode(convert_to('todo:' || $1.id::text, 'utf-8'), 'base64')
$$ immutable language sql;
create index on todo (relay_id(todo.*));
```

**Comment by ruslantalpa** [comment]
the tutorial code has been reflected to show the correct ids. thank you
