### ISSUE TITLE
Cannot Start Service rabbitMQ

### ISSUE THREAD

**Issue by corepay** [subzerocloud/subzero-starter-kit#8]
Hello,

I tried `docker-compose up -d`  with both the CLI and git clone this repo and continue to get this error:

<img width="1083" alt="screen shot 2018-10-15 at 3 50 15 pm" src="https://user-images.githubusercontent.com/37046197/46974503-2c30d300-d092-11e8-9f34-2d4c0b15f458.png">

**Comment by ruslantalpa** [comment]
Untill i fix this in the repo (few hours), run
chmod +x rabbitmq/entrypoint.sh

Then it should work

**Comment by ruslantalpa** [comment]
thanks for the report, I changed the permissions of the file in the repo and the normal cli/clone steps should work
